name: debugger-action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
  with:

    env:

      ACTIONS_STEP_DEBUG: true
